filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

#      templates:
#        - condition:
#            contains:
#              docker.container.image: '*'
#          config:
#            - type: container
#              paths:
#                - /var/lib/docker/containers/${data.docker.container.id}/${data.docker.container.id}-json.log

#filebeat:
#  inputs:
#    -
#      paths:
#        - /var/log/syslog
#        - /var/log/auth.log
#      document_type: syslog
